title: Pooja Handicrafts
description: Beautiful handcrafted Mandirs, Swings, and Rocking Chairs.
url: "https://poojahandicrafts.store"
baseurl: "" # Leave this blank if using custom domain
theme: null

permalink: pretty
markdown: kramdown

author:
  name: Heena Soni
  email: tejrajsoni86@gmail.com

social:
  whatsapp: https://wa.me/9110529659
  instagram: https://instagram.com/pooja_handicrafts18

navbar:
  - title: Home
    url: /
  - title: Mandirs
    url: /mandirs
  - title: Swings
    url: /swings
  - title: Rocking Chairs
    url: /rocking-chairs
  - title: Contact
    url: /contact

footer:
  text: "© 2025 Pooja Handicrafts. All rights reserved."
